# Generated by Django 3.2.6 on 2021-09-22 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210922_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creation_time',
            new_name='created',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField()),
                ('value', models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
        ),
    ]
